name: Build MSVC & G++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  job:
    name: ${{ matrix.name }}-build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-latest-g++, windows-latest-cl.exe,]
        # For Windows msvc, for Linux gcc.
        include:
          - name: windows-latest-cl.exe
            os: windows-latest
            cxx: cl.exe
            cc: cl.exe
          - name: ubuntu-latest-g++
            os: ubuntu-latest
            cxx: g++
            cc: gcc     
            
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: lukka/get-cmake@latest
    
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install mesa-dev
      if: startsWith(matrix.name, 'ubuntu')
      run: sudo apt-get install xorg-dev libglu1-mesa-dev
      
    - name: configure and build
      uses: lukka/run-cmake@v3
      env:
        ENV_DIR: '${{ github.workspace }}'

      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/build/'
